### ISSUE TITLE
Instalation problem Windows 10 desktop

### ISSUE THREAD

**Issue by antyneutron** [voletro/wsa-toolbox#13]
hello
i wanna install package but i see error 
<img width="605" alt="error" src="https://user-images.githubusercontent.com/90155269/147284688-7822d6c8-7829-4248-bc34-9aa902e3c19e.png">

I use a windows 10 with any updates , so i must instal win 11 ?

**Comment by voletro** [comment]
You cannot use Windows 10 with WSA as it requires Windows 11. You will need to update to install the package.

**Comment by antyneutron** [comment]
ok thanks :)

so i cant use this coude my PC is to old for Win 11 🗡️
