### ISSUE TITLE
"No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by NoelleTGS** [voletro/wsa-toolbox#16]
Having troubles installing anything, neither the ones built into the app nor my own downloaded apks will install.

```Installing...
disconnected everything
cannot connect to 127.0.0.1:58526: No connection could be made because the target machine actively refused it. (10061)
Performing Push Install
adb: error: failed to get feature set: no devices/emulators found
The APK File has been installed. Shortcut Available in the Start Menu.
Press any key to continue . . .
```

**Comment by voletro** [comment]
Enable developer options in the Windows Subsystem For Android app.

**Comment by NoelleTGS** [comment]
I already have that enabled, no difference.
![image](https://user-images.githubusercontent.com/44215890/157168957-f161c77e-240e-4b91-8184-f19156a26d63.png)
