### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by artemgur** [voletro/wsa-toolbox#19]
When I start WSA Toolbox, in addition to the WSA Toolbox window a cmd window opens with the following content:

>C:\Users\artemgur\AppData\Local\Temp\7ZipSfx.001>я╗┐@echo off
>"я╗┐@echo" не является внутренней или внешней
>командой, исполняемой программой или пакетным файлом.

The locale is ru-RU.

"не является внутренней или внешней командой, исполняемой программой или пакетным файлом" is the localized "is not recognized as an internal or external command, operable program or batch file".

"я╗┐@echo" seem to be the result of an encoding issue.

I didn't risk checking if this error breaks the app functionality. Hard to say if the issue is purely cosmetical or not.

**Comment by voletro** [comment]
This project is now deprecated.
