### ISSUE TITLE
Worked first time. Now showing an error

### ISSUE THREAD

**Issue by FahadBinHussain** [voletro/wsa-toolbox#5]
Install APK File Button not working!

![image](https://user-images.githubusercontent.com/75292632/139531049-ec2f7567-c258-47be-b1dc-de0331dce8de.png)

And also everytime I run the exe, this also runs. What is this?

![image](https://user-images.githubusercontent.com/75292632/139531256-5420e995-96b8-41a1-b1b3-d0f29537146f.png)

**Comment by voletro** [comment]
1. Not sure why this is happening, will have a look.
2. This is the command prompt window that runs when you open the app. It is needed to run the app and use the quick install feature by dragging an apk onto the exe.
