### ISSUE TITLE
adb: error: failed to get feature set: device offline

### ISSUE THREAD

**Issue by ackervn** [voletro/wsa-toolbox#6]
When I click Install APK file or any Install... buttons ....
![image](https://user-images.githubusercontent.com/93516485/139648138-aea6a1b4-1b66-4306-8dc8-baf0c5520f90.png)

**Comment by vincentw56** [comment]
- Open Windows Subsystem for Android app on your PC.
- Find out the Developer mode option.
- Toggle the corresponding button to turn it on.
