### ISSUE TITLE
Weird characters (´╗┐) at the start of a batch file

### ISSUE THREAD

**Issue by rhemberger** [voletro/wsa-toolbox#8]
Hello, thank you for this nice tool.
There is a litlle problem with the encoding of the batch files as explained here:
https://superuser.com/questions/601282/%cc%81-is-not-recognized-as-an-internal-or-external-command
or here:
https://superuser.com/questions/769601/weird-characters-%C2%B4-at-the-start-of-a-batch-file

`´╗┐@echo off` cannot be executed

**Comment by voletro** [comment]
Seems to be an issue with the compiler I am using. I'll have a look at this. Thanks!
